[phases.setup]
cmds = ["curl -s https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer"]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader"]

[phases.build]
cmds = ["php artisan key:generate", "php artisan storage:link", "php artisan optimize"]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"

[watch]
files = ["composer.json", "composer.lock"]